### ISSUE TITLE
Migrer le repository vers l'organisation `gip-inclusion`

### ISSUE THREAD

**Issue by vmttn** [gip-inclusion/data-inclusion#138]
- [x] mettre à jour les références aux images docker de la registry
  - [x] dans le docker compose de deploiement https://github.com/betagouv/data-inclusion/blob/main/deployment/docker-compose.yml 
- [x] mettre à jour l'intégration GH sur scalingo pour toutes les apps
  - [x] https://dashboard.scalingo.com/apps/osc-secnum-fr1/data-inclusion-api-prod/deploy/config
  - [x] https://dashboard.scalingo.com/apps/osc-secnum-fr1/data-inclusion-siretisation-staging/deploy/config
  - [x] https://dashboard.scalingo.com/apps/osc-secnum-fr1/data-inclusion-scripts-staging/deploy/config
- sentry ?

**Comment by vperron** [comment]
cc @vmttn un sujet similaire est en courts côté Emplois, et nous aurons besoin de quelqu'un de beta pour chanegr l'ownership du repo (ce qui permet de conserver tout l'historique de PR/Issues/etc)

Idealement on se synchronise et le copain de beta fait ça dans le meme mouvement ?

**Comment by vperron** [comment]
cc https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository une redirection est mise en place de manière permanente, jusqu'à création d'un repo data-inclusion de nouveau chez betagouv.

**Comment by vperron** [comment]
Prévu le 15 Novembre 13h en synchrone avec Julien D.

**Comment by vperron** [comment]
- [x] Migrer le repository lui-même
- [x] Ajouter des teams data-inclusion et admins-data-inclusion conformément a la PSSI du GIP
- [ ] Investiguer le role du service prod avec Jeremy
- [x] Activre le secret tracker et autres réglages (branch protection main et *)
- [ ] Discuter avec valentin de mettre en place des PR obligatoires ou non (pas se marcher sur les pieds, lancer les checks...)
- [ ] Remplacer les occurrences de betagouv dans le code
- [ ] Remplacer les occurrences de betagouv dans le vault
- [ ] MAJ de l'intégration GH dans Scalingo
